apiVersion: v1
kind: pod
metadate:
  name: nodehelloworld.example.cpm
  lables: 
    app: helloworld
spec: 
  container:
  - name: K8s demo
    image: arjunachari12/k8s-demo
    ports:
    - name: nodejs-port
      containerPort: 3000
