apiVersion: v1
kind: ConfigMap
metadata:
  name: games-demo
data: 
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.prperties"
  game.properties:
    enemy.types=aliens,monsters
    player.maximum-lives=5
  User-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
