apiVersion: apps/v1
kind: replicaSet
metadata:
  name: helloworld-controller
  labels:
    app: elloworld
spec:
  replicas: 4
  selector: 
    matchLabels:
      app: helloworld
  template: 
    metadata: 
      app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: arhunachari12/k8s-demo
        ports:
        - name: nodejs-port
          containerPort: 3000
